# Generated by Django 4.2 on 2025-11-22 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_tempotp_recruiterprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiterprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='TempOTP',
        ),
        migrations.DeleteModel(
            name='RecruiterProfile',
        ),
    ]
